### ISSUE TITLE
Add "Get New Recipes" option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [6r4phy/rcdgo#28]
```
A new menu option "Get New Recipes" would show a list of sites to visit to 
download recipes. 

Possibly grab data from an xml file on caldwellcode/ for a dynamic list of 
sites to avoid hard coding urls into Bites and allow some monetizing.
e.g.
<recipesites>
<site title="Sams Seafood" url="www.sams.com" category="Seafood" />
<site title="Shaken not stirred" url="www.shaker.com" category="Alcoholic 
Beverages" />
</recipesites>
```

Original issue reported on code.google.com by `benny.ca...@gmail.com` on 28 Jul 2009 at 5:42

**Comment by 6r4phy** [comment]
A new menu option "Get New Recipes" would show a list of sites to visit to 
download recipes. 

Possibly grab data from an xml file on caldwellcode/ for a dynamic list of 
sites to avoid hard coding urls into Bites and allow some monetizing.
e.g.
<recipesites>
<site title="Sams Seafood" url="www.sams.com" category="Seafood" />
<site title="Shaken not stirred" url="www.shaker.com" category="Alcoholic 
Beverages" />
</recipesites>
